---
name: unit test

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  testunit:
    runs-on: [ self-hosted, 1ES.Pool=terraform-azurerm-avm-ptn-vnetgateway ]
    env:
      TF_IN_AUTOMATION: 1
      TF_VAR_enable_telemetry: false
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 #v4.1.2
      - name: Run Unit Tests
        shell: bash
        run: |
          set -e
          az login --identity --username $MSI_ID > /dev/null
          export ARM_SUBSCRIPTION_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .id')
          export ARM_TENANT_ID=$(az login --identity --username $MSI_ID | jq -r '.[0] | .tenantId')
          export ARM_CLIENT_ID=$(az identity list | jq -r --arg MSI_ID "$MSI_ID" '.[] | select(.principalId == $MSI_ID) | .clientId')
          docker run --rm \
            -v $(pwd):/src \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /src \
            --network=host \
            -e TF_IN_AUTOMATION \
            -e TF_VAR_enable_telemetry \
            -e MSI_ID \
            -e ARM_SUBSCRIPTION_ID \
            -e ARM_TENANT_ID \
            -e ARM_CLIENT_ID \
            -e ARM_USE_MSI=true \
            mcr.microsoft.com/azterraform:latest \
            sh -c "terraform init && terraform test -verbose"


